- script/seed.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/products.js
> Order Model complete & added items to seed

- script/seed.js
- server/db/models/index.js
> Associations Completed

- client/app.js
- client/components/allProducts.js
- client/components/cart.js
> added cart component

- server/api/cart.js
- server/api/users.js
> Fixed Cart backend bug

- client/components/CheckoutForm.js
> Checkout Form Componenet draft completed

- client/app.js
- client/components/allProducts.js
- client/store/reducer.js
> adding to cart

- client/store/reducer.js
- server/api/cart.js
> front-end routes to view items in cart

- client/components/cart.js
- client/components/index.js
- client/routes.js
> Add cart-component

- client/app.js
- client/components/CheckoutForm.js
- client/components/cart.js
- client/store/reducer.js
> working on form functionality

- client/components/navbar.js
- public/style.css
> added shopping cart

- client/app.js
- client/components/allProducts.js
- client/components/navbar.js
- client/components/singleProduct.js
- client/components/user.js
- client/store/reducer.js
- public/style.css
- server/api/products.js
> Single product

- client/store/user.spec.js
- script/seed.js
- server/api/products.spec.js
- server/db/models/cart.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/products.js
- server/db/models/user.js
> Refactor: #33: Updated Models Post Code Review

- server/api/cart.js
- server/db/models/order.js
> Refactor: #4: Refactor Cart API route

- .travis.yml
- server/api/users.js
> Protect routes

- server/api/cart.js
- server/db/models/order.js
> Chart refactor

- server/api/users.js
> Api route security

- client/components/allProducts.js
- client/components/cart.js
- client/store/cart.js
- client/store/index.js
- server/api/cart.js
- server/db/models/cart.js
- server/db/models/order.js
> Refactor: #3: getCart and CartComponent

- client/app.js
- client/components/admin/admin.js
- client/components/admin/adminAllProducts.js
- client/components/admin/adminView.js
- client/components/admin/allUsers.js
- client/components/allProducts.js
- client/components/cart.js
- client/components/navbar.js
- client/components/user.js
- client/routes.js
- client/store/cart.js
- client/store/index.js
- client/store/user.js
- client/store/usersForAdmin.js
- server/api/cart.js
- server/api/users.js
- server/db/models/cart.js
- server/db/models/order.js
> Pseudo master

- client/app.js
- client/components/CheckoutForm.js
- client/components/cart.js
- client/components/checkout.js
- client/store/index.js
- client/store/orders.js
- server/api/cart.js
- server/auth/index.js
> Checkout form3

- client/components/cart.js
- server/api/cart.js
- server/db/models/cart.js
> Cart refactor

- client/components/homepage.js
- client/store/products.js
- script/seed.js
- server/api/products.js
- server/db/models/products.js
> Sale games

- client/store/products.js
> BUG: #70: Defined my action

- client/store/user.spec.js
- server/api/users.spec.js
> Debug tests

- client/components/user-home.spec.js
> disabling broken tests

- client/components/cart.js
- client/store/products.js
> Bug: #82: duplicate div found in cart

- client/app.js
- client/components/admin/adminAllProducts.js
- client/components/allProducts.js
- client/components/navbar.js
- public/index.html
- public/style.css
> Style: #55: Add CSS styling

- client/components/allProducts.js
- client/components/cart.js
- client/components/navbar.js
- client/store/cart.js
- public/style.css
- public/style.css.rej
- server/api/cart.js
Bug: #54: Delete functionality bug resolved.
Styling: #86: Cart style added.
---
> Bug: #54: Styling: #86: Cart style + delete funcationality

- client/app.js
- client/components/homepage.js
- client/routes.js
- client/store/products.js
- server/api/products.js
> BUG: #70: Fixed error in API route

- client/components/Checkout/CheckoutForm.js
- server/api/products.js
> Payment form

- client/components/homepage.js
- server/api/products.js
- server/db/models/products.js
> REFACTOR: #70: HomePage shows producs but there is a bug

- client/components/user-home.spec.js
> bug: disabling broken test

- client/components/Checkout/CheckoutForm.js
- client/components/Checkout/completed.js
- client/routes.js
- server/api/products.js
- server/db/models/products.js
> FEATURE: #99: Created basic order confirmation page - more coming

- .travis.yml
> #64 travis: activate deployment

- client/components/allProducts.js
- client/components/homepage.js
- client/components/individualprod.js
> Single page updates

- client/components/singleProduct.js
> Refactor: #59: Added AddToCart from single item view

- script/seed.js
- server/db/models/products.js
> Update: Added more items to the seed

- client/components/Checkout/CheckoutForm.js
- client/components/account.js
- client/components/orderHistory.js
- client/store/cart.js
- client/store/orders.js
- client/store/products.js
- server/api/cart.js
> Order history

- client/components/admin/NewBoardGameForm.js
- client/components/admin/adminAllProducts.js
- client/store/products.js
- server/api/products.js
- server/db/models/products.js
> bug: reintegrating board game form

- client/components/addToCart.js
- client/components/allProducts.js
- client/components/cart.js
- client/components/cartQuantityForm.js
- client/components/homepage.js
- client/components/individualprod.js
- client/components/singleProduct.js
- client/store/cart.js
- client/store/orders.js
- server/api/cart.js
Refactor: #116: Updated cart post api request to be called via react redux store instead of directly from the react components
Feature #57: Added a new feature for users to be able to update quantity of items in their cart
---
> Refactor: #116, Feature #57

- client/components/orderHistory.js
- client/components/sortOrders.js
> bug: previous orders are now grouped together by orderId

- client/app.js
- client/components/productsByTag.js
- client/routes.js
- client/store/products.js
- server/api/products.js
- server/db/models/products.js
> Tag search

- client/components/cart.js
> Bug: #120: fix cart view to show items when there is no item in the cart

- client/components/Checkout/stripe-checkout.js
- package-lock.json
- package.json
- server/api/cart.js
- server/email.js
Feature #61: Stripe payment set up
---
> Feature: #62: Set up email confirmation for orders

- client/components/productsByTag.js
- client/components/singleProduct.js
- client/routes.js
- client/store/products.js
- server/api/products.js
> BUG: #121: Working on frontend of searching by tag

- client/components/footer/footer.js
- public/style.css
> Style: #126: Added styling for footer

- client/components/cartTotal.js
- client/components/navbar.js
> feature: can view total number of items in the cart

- client/components/cartTotal.js
- client/components/navbar.js
> bug: fixed cart bug

- client/components/productsByTag.js
- client/routes.js
- client/store/products.js
> Tagstagstags

- client/components/admin/updateProduct.js
- client/components/singleProduct.js
- client/store/index.js
- client/store/product.js
- client/store/products.js
> bug: refactored product state

- client/components/singleProduct.js
> bug: single product price is in dollars no cents

- client/components/productsByTag.js
- script/seed.js
> Refactor: #121: Tags funtional! & Added to seed

- client/components/allProducts.js
- client/components/homepage.js
- client/components/productsByTag.js
- client/components/tagList.js
> Feature: #121: Added Taglist to hompage, allproducts, and the tag page

- client/components/homepage.js
- client/components/individualprod.js
> BUGFIX: Fixed some routing on the individual products

- client/components/admin/adminAllProducts.js
- client/components/admin/updateProduct.js
- client/store/product.js
- client/store/products.js
- server/api/index.js
- server/api/products.js
> bug: don't need to reload when updating a product

- client/store/products.js
- server/api/products.js
> bug: fixed add reducer and post route

- client/components/admin/adminAllProducts.js
- public/style.css
> FEATURE: #161: Adding in more styling on the admin page

- client/components/productsByTag.js
> REFACTOR: #121: Final edit on tags, I promise

- client/components/admin/adminAllProducts.js
- client/components/allProducts.js
- client/components/individualprod.js
- client/components/singleProduct.js
- public/style.css
> Refactor: #161: Added a bit more admin styling

- client/components/addToCart.js
- client/components/admin/adminAllProducts.js
- client/components/tagList.js
- public/index.html
- public/style.css
- server/db/models/products.js
> Feature: Sale items now really do compare to MSRP value

- client/components/homepage.js
- client/components/orderHistory.js
- public/style.css
> Refactor: #161: CSS styling

- client/components/navbar.js
- client/components/productsByTag.js
- public/style.css
> Feature: #161: more CSS

- server/db/models/products.spec.js
> Tests: product model class methods

- client/components/Checkout/CheckoutForm.js
- client/components/Checkout/checkout.js
- client/components/Checkout/stripe-checkout.js
- package-lock.json
- package.json
- server/api/cart.js
> Feature: #61: React component added for payment

- client/components/Checkout/stripe-checkout.js
> Bug: #174: Fix production deployment issue

- client/components/Checkout/stripe-checkout.js
> Bug: #174: Heroku deployment issues
